Updated manual credential entry in Client
BC-SECURITY/empire-docs pull request #6
Opened 2022-02-27 02:47 UTC by mwnickerson

Updated the process of how to add credentials manually to the Client documentation.

2022-03-06 17:00 UTC, vinnybod requested changes

2022-03-06 17:00 UTC, vinnybod commented on interfaces/client.md
> +=======
```suggestion
```

2022-03-06 17:00 UTC, vinnybod commented on interfaces/client.md
> +>>>>>>> Stashed changes
```suggestion
```

2022-03-06 17:00 UTC, vinnybod commented on interfaces/client.md
> +![manually-add-credentials](https://github.com/mwnickerson/empire-docs/blob/main/interfaces/images/manual-credentials.png)
You can upload this image to GitHub by dragging it into an issue/pr comment to get a static url like: `https://user-images.githubusercontent.com/<name>.png`. This is preferred to pointing to your forked repo.

2022-03-07 15:25 UTC, mwnickerson commented
<img width="819" alt="manual-credentials" src="https://user-images.githubusercontent.com/82531659/157063795-5f9f74a4-b698-4815-806f-ba9990b41e11.png">

2022-03-07 15:44 UTC, mwnickerson reviewed
I updated the docuements with a static link of the image I put in the comment box.

2022-05-24 03:29 UTC, merged